mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: localhost
    port: 1883
    keepalive: 60
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: sensor_msgs.msg:NavSatFix
    topic_from: /mavros/global_position/global
    topic_to: current_location

  #- factory: mqtt_bridge.bridge:RosToMqttBridge
  #  msg_type: sensor_msgs.msg:Range
  #  topic_from: /range_data
  #  topic_to: range_data

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /range_location
    topic_to: range_location

  # - factory: mqtt_bridge.bridge:MqttToRosBridge
  #   msg_type: std_msgs.msg:Bool
  #   topic_from: ping
  #   topic_to: /pong
