set(_CATKIN_CURRENT_PACKAGE "mqtt_bridge")
set(mqtt_bridge_VERSION "0.1.5")
set(mqtt_bridge_MAINTAINER "Junya Hayashi <junya.hayashi@groove-x.com>")
set(mqtt_bridge_PACKAGE_FORMAT "2")
set(mqtt_bridge_BUILD_DEPENDS )
set(mqtt_bridge_BUILD_EXPORT_DEPENDS )
set(mqtt_bridge_BUILDTOOL_DEPENDS "catkin")
set(mqtt_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(mqtt_bridge_EXEC_DEPENDS "rospy" "rosbridge_library" "std_msgs")
set(mqtt_bridge_RUN_DEPENDS "rospy" "rosbridge_library" "std_msgs")
set(mqtt_bridge_TEST_DEPENDS )
set(mqtt_bridge_DOC_DEPENDS )
set(mqtt_bridge_DEPRECATED "")