set(_CATKIN_CURRENT_PACKAGE "rover")
set(rover_VERSION "0.0.0")
set(rover_MAINTAINER "Bill Berzinskas <bberzinskas@gmail.com>")
set(rover_PACKAGE_FORMAT "1")
set(rover_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "rosserial_python" "sensor_msgs" "std_msgs")
set(rover_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "rospy" "rosserial_python" "sensor_msgs" "std_msgs")
set(rover_BUILDTOOL_DEPENDS "catkin")
set(rover_BUILDTOOL_EXPORT_DEPENDS )
set(rover_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "rosserial_python" "sensor_msgs" "std_msgs")
set(rover_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "rosserial_python" "sensor_msgs" "std_msgs")
set(rover_TEST_DEPENDS )
set(rover_DOC_DEPENDS )
set(rover_DEPRECATED "")